### PR TITLE
Restructuring for the addition of resolved CAD files and shared images

### PR DESCRIPTION
**Pull request by jttaufa**
Changes to directory structure and addition of missing CAD files and images

### CODE REVIEW

**Comment by K-Meech** [comment]
Thanks @jttaufa for the PR! It's great to have the updated solidworks files. 

I was wondering - would it be possible to export these from solidworks as .STEP or another format that can be opened in more programs? As solidworks licenses are expensive, it would be nice to have them available in a format that can be opened in free viewers also. Ideally we could have a folder of .STEP files and a folder of solidworks files for each of these.

**Comment by jttaufa** [comment]
Done! Hopefully these STEP files should have the sub-assemblies and parts embedded in them? I think only SW2023 allowed for exporting the STEPS as linked directories rather than a single file.

**Comment by K-Meech** [comment]
Thanks @jttaufa ! Sorry for the delay in getting back to you. 
Could you change this PR to be against the 'update_cad' branch rather than 'main'? Then I can update some of the READMEs and rearrange a few files before I merge into the main branch.

**Comment by jttaufa** [comment]
No worries. Hopefully I've done that correctly!

**Comment by K-Meech** [comment]
Thanks @jttaufa ! I'll merge now - sorry again for being so slow on this

**Pull request merged**
